# -*- coding: utf-8 -*-
"""Paper B task 5 — the eICU port-Hamiltonian experiment, replicated on INSPIRE, plus the
multi-step test eICU could not support.

`RESULTS_v7_port_rollout.md` closes with one limitation above the others: eICU gives a
single `pre -> post` pair per episode, so every rollout beyond step 1 is extrapolation of
the learned map with nothing to check it against. INSPIRE gives 5-minute trajectories, so
the rollout can be scored against what actually happened.

    eICU     x = (CO, SBP, DBP, HR)        2,720 pairs, 1,445 patients, 208 US hospitals, ICU
    INSPIRE  x = (CI*BSA, art_sbp, art_dbp, hr)
                                          101,688 transitions, 2,501 operations, SNUH, theatre

Same state, same four drug mechanisms, same models, same protocol. Two countries, two care
settings, two institutions.

WHAT IS NEW HERE
    Multi-step rollout scored against the observed trajectory at 1, 3, 6 and 12 steps
    (5-60 minutes), against a persistence baseline at the same horizon. A model that is
    accurate at one step and useless at twelve is a bad simulator, and until now nothing in
    Paper B could detect that.

A PROPERTY OF THE DATA THAT MUST BE STATED
    INSPIRE winsorises every measurement to its 2.5-97.5 percentile before release, so
    art_sbp spans only 72-160 mmHg and hr only 46-108 /min. Trajectories therefore start
    well inside the physiological box, and any exit during rollout is generated by the
    model rather than inherited from the data. That makes the admissibility test cleaner
    than in eICU, and it makes the absolute exit rates not comparable between the two.

Usage:  python3 port_rollout_inspire.py --list | --job N | --summary
"""
import argparse, json, os, sys, time
import numpy as np, pandas as pd
import torch, torch.nn as nn, torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GroupShuffleSplit
from sklearn.metrics import r2_score

from port_rollout import (MODELS, LETTERS, SEEDS, NX, NU, MECHS, BOX,
                          EPOCHS, BATCH, LR, WD, PATIENCE,
                          psd_violations, skew_error, rollout, energy_report)

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "inspire_traj.csv")
STORE = os.path.join(HERE, "results_port_rollout_inspire.json")
SCOLS = ["co", "art_sbp", "art_dbp", "hr"]
DRUG = {"nepi": "vasopressor", "ntgi": "vasodilator", "dobui": "inotrope",
        "mlni": "inotrope", "epii": "vasopressor_inotrope", "dopai": "vasopressor_inotrope"}
HORIZONS = [1, 3, 6, 12]


def load(train_mask=None):
    d = pd.read_csv(SRC)
    d = d[d.contiguous.astype(bool)].reset_index(drop=True)
    fit = np.ones(len(d), bool) if train_mask is None else train_mask
    U = np.zeros((len(d), NU), np.float32)
    for col, mech in DRUG.items():
        v = np.log1p(d[col].to_numpy())
        ref = v[fit & (v > 0)]
        mu, sd = (ref.mean(), ref.std()) if ref.size > 2 else (0.0, 1.0)
        z = np.where(v > 0, (v - mu) / (sd + 1e-9), 0.0)
        U[:, MECHS.index(mech)] += z            # mechanisms sum, as in eICU
    X = d[SCOLS].to_numpy(np.float32)
    Y = d[[f"next_{c}" for c in SCOLS]].to_numpy(np.float32)
    return X, U, Y, d.op_id.to_numpy(), d


def multistep(net, d, idx, scX, seeds_u, horizons=HORIZONS):
    """Roll the learned map forward from each start and score against what happened.

    Only starts with `h` consecutive observed slots are used, and the true input at each
    step is supplied, so this measures the dynamics rather than input forecasting.
    """
    sub = d.iloc[idx]
    out = {}
    for h in horizons:
        # find windows of h+1 consecutive slots inside one operation
        g = sub.reset_index(drop=True)
        pos = {(o, s): i for i, (o, s) in enumerate(zip(g.op_id, g.slot))}
        starts = [i for i, (o, s) in enumerate(zip(g.op_id, g.slot))
                  if all((o, s + k) in pos for k in range(1, h + 1))]
        if len(starts) < 50:
            out[f"h{h}"] = None
            continue
        starts = np.array(starts)
        if len(starts) > 4000:
            starts = np.random.default_rng(0).choice(starts, 4000, replace=False)
        x = torch.tensor(scX.transform(g.loc[starts, SCOLS].to_numpy(np.float32)))
        for k in range(h):
            uidx = np.array([pos[(g.op_id[i], g.slot[i] + k)] for i in starts])
            u = torch.tensor(seeds_u[uidx])
            x = net(x, u)[0].detach()
            x = torch.nan_to_num(x, nan=0.0, posinf=1e6, neginf=-1e6).clamp(-1e4, 1e4)
        tgt_idx = np.array([pos[(g.op_id[i], g.slot[i] + h)] for i in starts])
        true = scX.transform(g.loc[tgt_idx, SCOLS].to_numpy(np.float32))
        pers = scX.transform(g.loc[starts, SCOLS].to_numpy(np.float32))
        pred = x.numpy()
        mse = float(np.mean((pred - true) ** 2))
        pmse = float(np.mean((pers - true) ** 2))
        out[f"h{h}"] = {"n": int(len(starts)), "mse": round(mse, 5),
                        "persistence_mse": round(pmse, 5),
                        "skill": round(1 - mse / pmse, 4),
                        "r2_mean": round(float(np.mean(
                            [r2_score(true[:, j], pred[:, j]) for j in range(NX)])), 4)}
    return out


def run(letter, seed):
    X0, _, Y0, g0, _ = load()
    gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=seed)
    trv, te = next(gss.split(X0, Y0, g0))
    mask = np.zeros(len(X0), bool); mask[trv] = True
    X, U, Y, grp, d = load(train_mask=mask)

    gin = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=seed + 100)
    itr, iva = next(gin.split(X[trv], Y[trv], grp[trv]))
    tr, va = trv[itr], trv[iva]
    for a, b, nm in [(tr, te, "train/test"), (tr, va, "train/val"), (va, te, "val/test")]:
        assert not (set(grp[a]) & set(grp[b])), f"operation leakage: {nm}"

    scX = StandardScaler().fit(X[tr])
    Xtr, Xva, Xte = (scX.transform(X[i]).astype(np.float32) for i in (tr, va, te))
    Ytr, Yva, Yte = (scX.transform(Y[i]).astype(np.float32) for i in (tr, va, te))

    torch.manual_seed(seed)
    net = MODELS[letter]()
    opt = torch.optim.AdamW(net.parameters(), lr=LR, weight_decay=WD)
    sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, EPOCHS)
    dl = torch.utils.data.DataLoader(
        torch.utils.data.TensorDataset(torch.tensor(Xtr), torch.tensor(U[tr]),
                                       torch.tensor(Ytr)),
        batch_size=BATCH * 8, shuffle=True)          # 50x the eICU row count
    xv, uv, yv = torch.tensor(Xva), torch.tensor(U[va]), torch.tensor(Yva)

    t0 = time.time()
    best, best_state, best_ep, since = np.inf, None, -1, 0
    for ep in range(EPOCHS):
        net.train()
        for bx, bu, by in dl:
            opt.zero_grad()
            F.mse_loss(net(bx, bu)[0], by).backward()
            nn.utils.clip_grad_norm_(net.parameters(), 1.0)
            opt.step()
        sch.step()
        net.eval()
        v = float(F.mse_loss(net(xv, uv)[0], yv).detach())
        if v < best - 1e-6:
            best, best_ep, since = v, ep, 0
            best_state = {k: t.clone() for k, t in net.state_dict().items()}
        else:
            since += 1
            if since >= PATIENCE:
                break
    net.load_state_dict(best_state); net.eval()

    n_par = sum(p.numel() for p in net.parameters())
    n_dead = int(sum(p.numel() for _, p in net.named_parameters() if p.grad is None))
    res = {"dataset": "INSPIRE", "model": letter, "seed": seed,
           "n_params": int(n_par), "n_params_active": int(n_par - n_dead),
           "n_train": int(len(tr)), "n_val": int(len(va)), "n_test": int(len(te)),
           "n_train_ops": int(len(set(grp[tr]))), "n_test_ops": int(len(set(grp[te]))),
           "best_epoch": int(best_ep), "val_mse": round(best, 5),
           "train_seconds": round(time.time() - t0, 1)}

    xt, ut = torch.tensor(Xte), torch.tensor(U[te])
    pred, H, R, J = net(xt, ut)
    pred = pred.detach().numpy()
    res["onestep_mse"] = round(float(np.mean((pred - Yte) ** 2)), 5)
    res["onestep_r2_mean"] = round(float(np.mean(
        [r2_score(Yte[:, i], pred[:, i]) for i in range(NX)])), 4)
    pm = float(np.mean((Xte - Yte) ** 2))
    res["persistence_mse"] = round(pm, 5)
    res["persistence_r2_mean"] = round(float(np.mean(
        [r2_score(Yte[:, i], Xte[:, i]) for i in range(NX)])), 4)
    res["skill_vs_persistence"] = round(1 - res["onestep_mse"] / pm, 4)

    nps, rmin = psd_violations(R)
    res["structure"] = {"R_nonpsd": nps, "R_min_rel": rmin, "J_skew_maxerr": skew_error(J),
                        "H_negative": int((H.detach() < 0).sum()) if H is not None else None,
                        "n": int(len(xt))}

    # NEW: multi-step against the observed trajectory
    res["multistep"] = multistep(net, d, te, scX, U)

    # passivity + admissibility, identical conditions to the eICU run
    gen = torch.Generator().manual_seed(seed + 7)
    lo = torch.tensor([[BOX[v][0] for v in ["co", "sbp", "dbp", "hr"]]])
    hi = torch.tensor([[BOX[v][1] for v in ["co", "sbp", "dbp", "hr"]]])
    mu_t = torch.tensor(scX.mean_, dtype=torch.float32)
    sd_t = torch.tensor(scX.scale_, dtype=torch.float32)
    box_u = ((torch.rand(min(len(xt), 4000), NX, generator=gen) * (hi - lo) + lo) - mu_t) / sd_t
    sub = torch.arange(min(len(xt), 4000))
    res["first_step_norm"] = {}
    for tag, uu, x0, ns in [("drug", ut[sub], xt[sub], 200),
                            ("zero_input", torch.zeros_like(ut[sub]), xt[sub], 200),
                            ("box_uniform", ut[sub], box_u, 200),
                            ("dose_x5", ut[sub] * 5.0, xt[sub], 200),
                            ("recover_6sig", ut[sub],
                             torch.randn(len(sub), NX, generator=gen) * 6.0, 200)]:
        res["first_step_norm"][tag] = round(float(
            (net(x0.clone(), uu)[0].detach() - x0).norm(dim=1).median()), 4)
        r = rollout(net, x0.clone(), uu, ns, scX)
        Ht, mv = r.pop("_H"), r.pop("_move")
        if tag == "zero_input":
            r["energy"] = energy_report(Ht, mv)
        res[f"rollout_{tag}"] = r
    return res


def jobs():
    return [dict(letter=L, seed=s) for s in SEEDS for L in LETTERS]


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--job", type=int, default=None)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--summary", action="store_true")
    a = ap.parse_args()
    J = jobs()

    if a.list:
        for k, j in enumerate(J):
            print(f"{k:2d}  model {j['letter']:2s}  seed {j['seed']}")
        sys.exit(0)

    if a.summary:
        rows = json.load(open(STORE))
        rec = []
        for r in rows:
            e = ((r["rollout_zero_input"].get("energy") or {}).get("moving_steps")) or {}
            ms = r["multistep"]
            rec.append({"model": r["model"], "seed": r["seed"],
                        "R2_1step": r["onestep_r2_mean"],
                        "skill_1": r["skill_vs_persistence"],
                        **{f"skill_h{h}": (ms.get(f"h{h}") or {}).get("skill")
                           for h in HORIZONS},
                        "gain_u0": e.get("frac_gain_relative"),
                        "Rnpsd": r["structure"]["R_nonpsd"],
                        "ok_box": r["rollout_box_uniform"]["frac_admissible"],
                        "ok_6s": r["rollout_recover_6sig"]["frac_admissible"],
                        "step1_6s": r["first_step_norm"]["recover_6sig"]})
        d = pd.DataFrame(rec)
        pd.set_option("display.width", 220)
        print("--- per run ---")
        print(d.sort_values(["model", "seed"]).to_string(index=False))
        print("\n--- by model (mean over seeds) ---")
        print(d.drop(columns="seed").groupby("model").mean(numeric_only=True)
              .round(4).to_string())
        print(f"\npersistence one-step R2: "
              f"{np.mean([r['persistence_r2_mean'] for r in rows]):.4f}")
        sys.exit(0)

    j = J[a.job]
    r = run(j["letter"], j["seed"])
    prev = json.load(open(STORE)) if os.path.exists(STORE) else []
    prev = [x for x in prev if not (x["model"] == r["model"] and x["seed"] == r["seed"])]
    json.dump(prev + [r], open(STORE, "w"), indent=1, default=float)
    e = ((r["rollout_zero_input"].get("energy") or {}).get("moving_steps")) or {}
    ms = " ".join(f"h{h}={(r['multistep'].get(f'h{h}') or {}).get('skill')}" for h in HORIZONS)
    print(f"[{a.job}] {r['model']:2s} s{r['seed']} R2_1={r['onestep_r2_mean']} | {ms} | "
          f"gain_u0={e.get('frac_gain_relative')} Rnpsd={r['structure']['R_nonpsd']} | "
          f"ok_box={r['rollout_box_uniform']['frac_admissible']} ({r['train_seconds']}s)")
